import { getDb } from "../api/queries/connection";
import {
  collections,
  products,
  projects,
  showroomInfo,
  teamMembers,
} from "./schema";

async function seed() {
  const db = getDb();
  console.log("Seeding database...");

  // Seed collections
  await db.insert(collections).values([
    {
      name: "Pietra Marble",
      slug: "pietra-marble",
      description:
        "The timeless elegance of marble, reimagined in durable porcelain. Four curated colours from pure white to dramatic charcoal, each with authentic veining that tells a story of geological beauty.",
      shortDescription: "4 colours · 6 sizes · matching mosaics",
      look: "marble",
      category: "floor_wall",
      images: ["/images/collections/pietra.jpg", "/images/hero/bathroom.jpg"],
      featured: true,
      meta: JSON.stringify({
        colours: ["Bianco", "Grigio", "Crema", "Nero"],
        sizes: ["12x24", "24x24", "24x48", "32x32"],
        matching: ["mosaic", "trim", "bullnose"],
      }),
    },
    {
      name: "Urban Concrete",
      slug: "urban-concrete",
      description:
        "Industrial concrete aesthetics meet modern porcelain technology. Three grey tones that capture the raw beauty of cast concrete — perfect for contemporary lofts, offices, and minimalist homes.",
      shortDescription: "3 colours · 4 sizes · industrial modern",
      look: "concrete",
      category: "floor_wall",
      images: ["/images/collections/urban.jpg", "/images/rooms/living.jpg"],
      featured: true,
      meta: JSON.stringify({
        colours: ["Light Grey", "Medium Grey", "Dark Grey"],
        sizes: ["12x24", "24x24", "24x48"],
        matching: ["mosaic"],
      }),
    },
    {
      name: "Coastal Stone",
      slug: "coastal-stone",
      description:
        "Soft, natural stone-look porcelain inspired by windswept coastal cliffs. Warm beige and sand tones that bring an organic, relaxed feel to any space.",
      shortDescription: "3 colours · 5 sizes · indoor/outdoor",
      look: "stone",
      category: "floor_wall",
      images: ["/images/collections/swatches.jpg", "/images/hero/terrace.jpg"],
      featured: false,
      meta: JSON.stringify({
        colours: ["Sand", "Beige", "Ivory"],
        sizes: ["12x24", "24x24", "24x48", "16x32"],
        matching: ["mosaic", "trim"],
      }),
    },
    {
      name: "Heritage Wood",
      slug: "heritage-wood",
      description:
        "European oak-inspired porcelain planks that deliver the warmth of wood with the durability of tile. Perfect for bathrooms, basements, and high-traffic areas where real wood isn't practical.",
      shortDescription: "4 colours · plank format · waterproof",
      look: "wood",
      category: "floor_wall",
      images: ["/images/rooms/outdoor.jpg", "/images/projects/project3.jpg"],
      featured: false,
      meta: JSON.stringify({
        colours: ["Natural Oak", "Smoked Oak", "Grey Oak", "Walnut"],
        sizes: ["6x36", "8x48", "10x60"],
        matching: ["trim"],
      }),
    },
    {
      name: "Terrazzo Remix",
      slug: "terrazzo-remix",
      description:
        "Bold terrazzo patterns reimagined for modern spaces. Large-format tiles with playful chip patterns that make a statement on floors and walls alike.",
      shortDescription: "2 colours · large format · bold pattern",
      look: "terrazzo",
      category: "floor_wall",
      images: ["/images/projects/project7.jpg", "/images/projects/project4.jpg"],
      featured: false,
      meta: JSON.stringify({
        colours: ["Classic", "Pastel"],
        sizes: ["24x24", "24x48", "32x32"],
        matching: ["mosaic"],
      }),
    },
    {
      name: "Casa Terra",
      slug: "casa-terra",
      description:
        "Mediterranean-inspired clay and terracotta tones. Warm, earthy colours that evoke sun-baked villas and artisan craftsmanship. Ideal for creating cozy, inviting spaces.",
      shortDescription: "4 colours · handmade look · artisan",
      look: "stone",
      category: "floor_wall",
      images: ["/images/hero/terrace.jpg", "/images/projects/project11.jpg"],
      featured: false,
      meta: JSON.stringify({
        colours: ["Terracotta", "Cotto", "Sand", "Clay"],
        sizes: ["12x24", "16x16", "8x8"],
        matching: ["mosaic", "trim"],
      }),
    },
  ]);

  console.log("Collections seeded");

  // Seed products
  await db.insert(products).values([
    // Pietra Marble products
    {
      name: "Bianco Polished 24x48",
      slug: "bianco-polished-24x48",
      category: "tile",
      subcategory: "floor_tile",
      collectionId: 1,
      room: "bathroom",
      look: "marble",
      colour: "white",
      size: "24x48",
      finish: "polished",
      useCase: "floor",
      material: "porcelain",
      thickness: "10mm",
      rectified: true,
      indoorOutdoor: "indoor",
      floorWall: "both",
      showerSafe: true,
      slipRating: "R9",
      frostResistant: false,
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Italy",
      cartonCoverage: 11.64,
      piecesPerBox: 2,
      weightPerBox: 22.5,
      sku: "PTR-BIA-2448-POL",
      price: 12.5,
      stockStatus: "in_stock",
      stockQuantity: 240,
      shortDescription:
        "Pure white marble-look porcelain with delicate grey veining. Polished finish for elegant interiors.",
      featured: true,
      images: ["/images/collections/pietra.jpg", "/images/hero/bathroom.jpg"],
      rating: 4.8,
      reviewCount: 24,
    },
    {
      name: "Grigio Honed 24x24",
      slug: "grigio-honed-24x24",
      category: "tile",
      subcategory: "floor_tile",
      collectionId: 1,
      room: "kitchen",
      look: "marble",
      colour: "grey",
      size: "24x24",
      finish: "matte",
      useCase: "floor",
      material: "porcelain",
      thickness: "10mm",
      rectified: true,
      indoorOutdoor: "indoor",
      floorWall: "both",
      showerSafe: true,
      slipRating: "R10",
      frostResistant: false,
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Italy",
      cartonCoverage: 7.75,
      piecesPerBox: 2,
      weightPerBox: 18.0,
      sku: "PTR-GRI-2424-HON",
      price: 10.75,
      stockStatus: "in_stock",
      stockQuantity: 180,
      shortDescription:
        "Soft grey marble-look with honed matte finish. Perfect for modern kitchens and bathrooms.",
      featured: false,
      images: ["/images/hero/kitchen.jpg"],
      rating: 4.6,
      reviewCount: 18,
    },
    {
      name: "Bianco Mosaic Hexagon",
      slug: "bianco-mosaic-hex",
      category: "mosaic",
      collectionId: 1,
      room: "bathroom",
      look: "marble",
      colour: "white",
      size: "12x12",
      finish: "polished",
      useCase: "shower_wall",
      material: "porcelain",
      thickness: "8mm",
      rectified: true,
      indoorOutdoor: "indoor",
      floorWall: "wall",
      showerSafe: true,
      slipRating: "R9",
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Italy",
      cartonCoverage: 10.0,
      piecesPerBox: 10,
      weightPerBox: 12.0,
      sku: "PTR-BIA-MOS-HEX",
      price: 18.5,
      stockStatus: "in_stock",
      stockQuantity: 95,
      shortDescription:
        "Hexagonal mosaic mesh-mounted sheets. Perfect for shower floors and feature walls.",
      featured: true,
      images: ["/images/hero/bathroom.jpg"],
      rating: 4.9,
      reviewCount: 31,
    },
    // Urban Concrete products
    {
      name: "Urban Light 24x48",
      slug: "urban-light-24x48",
      category: "tile",
      subcategory: "floor_tile",
      collectionId: 2,
      room: "living",
      look: "concrete",
      colour: "grey",
      size: "24x48",
      finish: "matte",
      useCase: "floor",
      material: "porcelain",
      thickness: "10mm",
      rectified: true,
      indoorOutdoor: "indoor",
      floorWall: "both",
      showerSafe: false,
      slipRating: "R9",
      frostResistant: false,
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Spain",
      cartonCoverage: 11.64,
      piecesPerBox: 2,
      weightPerBox: 21.0,
      sku: "URB-LGT-2448-MAT",
      price: 9.25,
      stockStatus: "in_stock",
      stockQuantity: 320,
      shortDescription:
        "Light grey concrete-look in large format. Industrial chic for contemporary spaces.",
      featured: true,
      images: ["/images/collections/urban.jpg"],
      rating: 4.5,
      reviewCount: 15,
    },
    {
      name: "Urban Dark 24x24",
      slug: "urban-dark-24x24",
      category: "tile",
      subcategory: "floor_tile",
      collectionId: 2,
      room: "commercial",
      look: "concrete",
      colour: "black",
      size: "24x24",
      finish: "textured",
      useCase: "floor",
      material: "porcelain",
      thickness: "12mm",
      rectified: true,
      indoorOutdoor: "both",
      floorWall: "floor",
      showerSafe: false,
      slipRating: "R11",
      frostResistant: true,
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Spain",
      cartonCoverage: 7.75,
      piecesPerBox: 2,
      weightPerBox: 20.5,
      sku: "URB-DRK-2424-TEX",
      price: 10.5,
      stockStatus: "in_stock",
      stockQuantity: 150,
      shortDescription:
        "Dark charcoal concrete-look with textured anti-slip finish. Suitable for indoor and outdoor use.",
      featured: false,
      images: ["/images/rooms/living.jpg"],
      rating: 4.4,
      reviewCount: 12,
    },
    // Heritage Wood products
    {
      name: "Natural Oak Plank 8x48",
      slug: "natural-oak-plank-8x48",
      category: "tile",
      subcategory: "floor_tile",
      collectionId: 4,
      room: "living",
      look: "wood",
      colour: "beige",
      size: "8x48",
      finish: "matte",
      useCase: "floor",
      material: "porcelain",
      thickness: "10mm",
      rectified: true,
      indoorOutdoor: "indoor",
      floorWall: "floor",
      showerSafe: false,
      slipRating: "R9",
      frostResistant: false,
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Turkey",
      cartonCoverage: 12.92,
      piecesPerBox: 4,
      weightPerBox: 19.5,
      sku: "HW-NAT-848-MAT",
      price: 8.75,
      stockStatus: "in_stock",
      stockQuantity: 400,
      shortDescription:
        "Warm natural oak plank porcelain. Waterproof alternative to hardwood flooring.",
      featured: true,
      images: ["/images/projects/project3.jpg"],
      rating: 4.7,
      reviewCount: 42,
    },
    {
      name: "Smoked Oak Plank 6x36",
      slug: "smoked-oak-plank-6x36",
      category: "tile",
      subcategory: "floor_tile",
      collectionId: 4,
      room: "kitchen",
      look: "wood",
      colour: "grey",
      size: "6x36",
      finish: "matte",
      useCase: "floor",
      material: "porcelain",
      thickness: "9mm",
      rectified: true,
      indoorOutdoor: "indoor",
      floorWall: "floor",
      showerSafe: false,
      slipRating: "R9",
      frostResistant: false,
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Turkey",
      cartonCoverage: 10.5,
      piecesPerBox: 7,
      weightPerBox: 16.0,
      sku: "HW-SMK-636-MAT",
      price: 7.25,
      stockStatus: "in_stock",
      stockQuantity: 280,
      shortDescription:
        "Smoked grey oak plank for a modern Scandinavian look. Easy maintenance.",
      featured: false,
      images: ["/images/projects/project8.jpg"],
      rating: 4.3,
      reviewCount: 19,
    },
    // Wall tiles
    {
      name: "Subway White Gloss 3x12",
      slug: "subway-white-gloss-3x12",
      category: "tile",
      subcategory: "wall_tile",
      room: "kitchen",
      look: "plain",
      colour: "white",
      size: "3x12",
      finish: "polished",
      useCase: "backsplash",
      material: "ceramic",
      thickness: "8mm",
      rectified: false,
      indoorOutdoor: "indoor",
      floorWall: "wall",
      showerSafe: true,
      slipRating: "R9",
      waterAbsorption: "0.5-3%",
      countryOfOrigin: "Mexico",
      cartonCoverage: 10.44,
      piecesPerBox: 42,
      weightPerBox: 14.2,
      sku: "SUB-WHT-312-GLS",
      price: 3.5,
      stockStatus: "in_stock",
      stockQuantity: 600,
      shortDescription:
        "Classic white subway tile with glossy finish. The timeless backsplash choice.",
      featured: true,
      images: ["/images/rooms/kitchen.jpg"],
      rating: 4.8,
      reviewCount: 67,
    },
    {
      name: "Subway Cream Handmade 3x12",
      slug: "subway-cream-handmade-3x12",
      category: "tile",
      subcategory: "wall_tile",
      room: "bathroom",
      look: "plain",
      colour: "beige",
      size: "3x12",
      finish: "polished",
      useCase: "backsplash",
      material: "ceramic",
      thickness: "8mm",
      rectified: false,
      indoorOutdoor: "indoor",
      floorWall: "wall",
      showerSafe: true,
      slipRating: "R9",
      waterAbsorption: "0.5-3%",
      countryOfOrigin: "Mexico",
      cartonCoverage: 10.44,
      piecesPerBox: 42,
      weightPerBox: 14.2,
      sku: "SUB-CRM-312-HMD",
      price: 4.25,
      stockStatus: "in_stock",
      stockQuantity: 450,
      shortDescription:
        "Handmade-look cream subway tile with slight surface variation. Warm and artisanal.",
      featured: false,
      images: ["/images/rooms/kitchen.jpg"],
      rating: 4.6,
      reviewCount: 28,
    },
    // Outdoor tiles
    {
      name: "Slate Charcoal 24x24 Anti-Slip",
      slug: "slate-charcoal-24x24",
      category: "tile",
      subcategory: "outdoor_tile",
      room: "outdoor",
      look: "stone",
      colour: "black",
      size: "24x24",
      finish: "textured",
      useCase: "outdoor",
      material: "porcelain",
      thickness: "20mm",
      rectified: true,
      indoorOutdoor: "outdoor",
      floorWall: "floor",
      showerSafe: false,
      slipRating: "R12",
      frostResistant: true,
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Italy",
      cartonCoverage: 7.75,
      piecesPerBox: 2,
      weightPerBox: 28.0,
      sku: "SLT-CHA-2424-20M",
      price: 14.5,
      stockStatus: "in_stock",
      stockQuantity: 120,
      shortDescription:
        "20mm thick 2cm porcelain pavers in charcoal slate-look. Frost-proof for Canadian winters.",
      featured: true,
      images: ["/images/hero/terrace.jpg", "/images/projects/project5.jpg"],
      rating: 4.9,
      reviewCount: 14,
    },
    {
      name: "Stone-Look Beige 24x24 Outdoor",
      slug: "stone-beige-24x24-outdoor",
      category: "tile",
      subcategory: "outdoor_tile",
      room: "outdoor",
      look: "stone",
      colour: "beige",
      size: "24x24",
      finish: "textured",
      useCase: "outdoor",
      material: "porcelain",
      thickness: "20mm",
      rectified: true,
      indoorOutdoor: "outdoor",
      floorWall: "floor",
      showerSafe: false,
      slipRating: "R11",
      frostResistant: true,
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Italy",
      cartonCoverage: 7.75,
      piecesPerBox: 2,
      weightPerBox: 27.0,
      sku: "STN-BGE-2424-20M",
      price: 13.25,
      stockStatus: "special_order",
      stockQuantity: 0,
      shortDescription:
        "Warm beige stone-look outdoor pavers. Elevated outdoor living for patios and pool decks.",
      featured: false,
      images: ["/images/projects/project11.jpg"],
      rating: 4.5,
      reviewCount: 8,
    },
    // Mosaics
    {
      name: "Hexagon Black & White Mosaic",
      slug: "hexagon-bw-mosaic",
      category: "mosaic",
      room: "bathroom",
      look: "luxury",
      colour: "black",
      size: "12x12",
      finish: "polished",
      useCase: "shower_floor",
      material: "porcelain",
      thickness: "6mm",
      rectified: true,
      indoorOutdoor: "indoor",
      floorWall: "both",
      showerSafe: true,
      slipRating: "R10",
      waterAbsorption: "<0.5%",
      countryOfOrigin: "China",
      cartonCoverage: 10.0,
      piecesPerBox: 10,
      weightPerBox: 9.5,
      sku: "MOS-HEX-BW-1212",
      price: 15.75,
      stockStatus: "in_stock",
      stockQuantity: 85,
      shortDescription:
        "Classic black and white hexagonal penny mosaic. Timeless pattern for floors and walls.",
      featured: false,
      images: ["/images/projects/project6.jpg"],
      rating: 4.7,
      reviewCount: 22,
    },
    // Slabs
    {
      name: "Calacatta Gold Porcelain Slab",
      slug: "calacatta-gold-slab",
      category: "slab",
      collectionId: 1,
      room: "kitchen",
      look: "marble",
      colour: "white",
      size: "slab",
      finish: "polished",
      useCase: "wall",
      material: "porcelain",
      thickness: "12mm",
      rectified: true,
      indoorOutdoor: "indoor",
      floorWall: "both",
      showerSafe: true,
      slipRating: "R9",
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Italy",
      cartonCoverage: 30.0,
      piecesPerBox: 1,
      weightPerBox: 65.0,
      sku: "SLB-CAL-GLD-12M",
      price: 45.0,
      stockStatus: "special_order",
      stockQuantity: 0,
      shortDescription:
        "Large-format Calacatta Gold porcelain slab with dramatic veining. For countertops and feature walls.",
      featured: true,
      images: ["/images/collections/pietra.jpg"],
      rating: 4.9,
      reviewCount: 7,
    },
    // Clearance items
    {
      name: "Travertine Cream 18x18",
      slug: "travertine-cream-18x18",
      category: "tile",
      subcategory: "floor_tile",
      room: "bathroom",
      look: "stone",
      colour: "beige",
      size: "18x18",
      finish: "honed",
      useCase: "floor",
      material: "porcelain",
      thickness: "9mm",
      rectified: false,
      indoorOutdoor: "indoor",
      floorWall: "both",
      showerSafe: true,
      slipRating: "R10",
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Turkey",
      cartonCoverage: 10.12,
      piecesPerBox: 4,
      weightPerBox: 17.5,
      sku: "TRV-CRM-1818-HON",
      price: 7.5,
      salePrice: 4.5,
      stockStatus: "clearance",
      stockQuantity: 12,
      clearance: true,
      clearanceCategory: "clearance_tiles",
      shortDescription:
        "Warm cream travertine-look porcelain. Discontinued line — last quantities available.",
      featured: false,
      images: ["/images/hero/bathroom.jpg"],
      rating: 4.2,
      reviewCount: 9,
    },
    {
      name: "Blue Glass Mosaic",
      slug: "blue-glass-mosaic",
      category: "mosaic",
      room: "bathroom",
      look: "luxury",
      colour: "blue",
      size: "12x12",
      finish: "polished",
      useCase: "wall",
      material: "glass",
      thickness: "8mm",
      rectified: true,
      indoorOutdoor: "indoor",
      floorWall: "wall",
      showerSafe: true,
      waterAbsorption: "0.5-3%",
      countryOfOrigin: "China",
      cartonCoverage: 10.0,
      piecesPerBox: 10,
      weightPerBox: 8.0,
      sku: "MOS-GLS-BLU-1212",
      price: 22.0,
      salePrice: 12.0,
      stockStatus: "clearance",
      stockQuantity: 5,
      clearance: true,
      clearanceCategory: "clearance_tiles",
      shortDescription:
        "Iridescent blue glass mosaic sheets. Stunning for pool waterlines and shower accents.",
      featured: false,
      images: ["/images/rooms/outdoor.jpg"],
      rating: 4.4,
      reviewCount: 6,
    },
    // Vanity
    {
      name: "Floating Vanity 48\" White Oak",
      slug: "floating-vanity-48-white-oak",
      category: "vanity",
      room: "bathroom",
      colour: "white",
      material: "wood",
      sku: "VAN-FLT-48-WOK",
      price: 899.0,
      stockStatus: "in_stock",
      stockQuantity: 8,
      shortDescription:
        "48-inch floating vanity in white oak finish with quartz countertop and undermount sink.",
      featured: false,
      images: ["/images/hero/bathroom.jpg"],
      rating: 4.6,
      reviewCount: 11,
    },
    // Sink
    {
      name: "Vessel Sink Round White Ceramic",
      slug: "vessel-sink-round-white",
      category: "sink",
      room: "bathroom",
      colour: "white",
      material: "ceramic",
      sku: "SNK-VES-RND-WHT",
      price: 189.0,
      stockStatus: "in_stock",
      stockQuantity: 15,
      shortDescription:
        "Elegant round ceramic vessel sink in glossy white. Above-counter installation.",
      featured: false,
      images: ["/images/hero/bathroom.jpg"],
      rating: 4.5,
      reviewCount: 14,
    },
    // Faucet
    {
      name: "Matte Black Single-Hole Faucet",
      slug: "matte-black-single-hole-faucet",
      category: "faucet",
      room: "bathroom",
      colour: "black",
      material: "metal",
      sku: "FCT-MBK-SNG-BLK",
      price: 245.0,
      stockStatus: "in_stock",
      stockQuantity: 12,
      shortDescription:
        "Modern matte black single-hole bathroom faucet with lever handle. Solid brass construction.",
      featured: false,
      images: ["/images/hero/bathroom.jpg"],
      rating: 4.7,
      reviewCount: 19,
    },
    // More products for variety
    {
      name: "Terrazzo Classic 24x24",
      slug: "terrazzo-classic-24x24",
      category: "tile",
      subcategory: "floor_tile",
      collectionId: 5,
      room: "commercial",
      look: "terrazzo",
      colour: "white",
      size: "24x24",
      finish: "polished",
      useCase: "floor",
      material: "porcelain",
      thickness: "10mm",
      rectified: true,
      indoorOutdoor: "indoor",
      floorWall: "both",
      showerSafe: false,
      slipRating: "R9",
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Italy",
      cartonCoverage: 7.75,
      piecesPerBox: 2,
      weightPerBox: 19.0,
      sku: "TRZ-CLS-2424-POL",
      price: 13.75,
      stockStatus: "in_stock",
      stockQuantity: 200,
      shortDescription:
        "Classic white terrazzo-look with multicolour chips. Playful yet sophisticated.",
      featured: false,
      images: ["/images/projects/project7.jpg"],
      rating: 4.5,
      reviewCount: 13,
    },
    {
      name: "Cement Tile Geometric Feature",
      slug: "cement-tile-geometric",
      category: "tile",
      subcategory: "wall_tile",
      room: "bathroom",
      look: "luxury",
      colour: "black",
      size: "8x8",
      finish: "matte",
      useCase: "wall",
      material: "porcelain",
      thickness: "10mm",
      rectified: false,
      indoorOutdoor: "indoor",
      floorWall: "wall",
      showerSafe: false,
      waterAbsorption: "<0.5%",
      countryOfOrigin: "Morocco",
      cartonCoverage: 5.44,
      piecesPerBox: 12,
      weightPerBox: 15.0,
      sku: "CEM-GEO-88-MAT",
      price: 8.5,
      stockStatus: "in_stock",
      stockQuantity: 180,
      shortDescription:
        "Bold geometric cement-look tiles in black, white, and terracotta. Statement feature walls.",
      featured: false,
      images: ["/images/projects/project9.jpg"],
      rating: 4.8,
      reviewCount: 17,
    },
  ]);

  console.log("Products seeded");

  // Seed projects
  await db.insert(projects).values([
    {
      name: "Oakville Master Ensuite",
      slug: "oakville-master-ensuite",
      category: "bathroom",
      location: "Oakville, ON",
      year: 2025,
      description:
        "A complete master ensuite renovation featuring large-format marble-look porcelain tiles, heated floors, frameless glass shower, and freestanding tub. The client wanted a spa-like retreat that felt both luxurious and functional.",
      productsUsed: "Bianco Polished 24x48, Grigio Honed 24x24, Bianco Mosaic Hexagon",
      images: ["/images/projects/project1.jpg"],
      featured: true,
    },
    {
      name: "Toronto Kitchen Renovation",
      slug: "toronto-kitchen-renovation",
      category: "kitchen",
      location: "Toronto, ON",
      year: 2025,
      description:
        "Full kitchen renovation with concrete-look floor tiles and herringbone subway tile backsplash. Warm wood island with brass accents. Open-concept layout connecting to dining area.",
      productsUsed: "Urban Light 24x48, Subway White Gloss 3x12",
      images: ["/images/projects/project2.jpg"],
      featured: true,
    },
    {
      name: "Yorkville Condo Flooring",
      slug: "yorkville-condo-flooring",
      category: "flooring",
      location: "Toronto, ON",
      year: 2024,
      description:
        "Wide-plank engineered hardwood look achieved with waterproof porcelain planks throughout the entire condo. Floor-to-ceiling windows showcase the stunning wood-look flooring.",
      productsUsed: "Natural Oak Plank 8x48",
      images: ["/images/projects/project3.jpg"],
      featured: true,
    },
    {
      name: "Mississauga Commercial Lobby",
      slug: "mississauga-commercial-lobby",
      category: "commercial",
      location: "Mississauga, ON",
      year: 2025,
      description:
        "Commercial office lobby with polished porcelain floor tiles in light beige marble look. Custom mosaic feature wall behind reception desk creates an impressive first impression.",
      productsUsed: "Bianco Polished 24x48, Terrazzo Classic 24x24",
      images: ["/images/projects/project4.jpg"],
      featured: true,
    },
    {
      name: "Richmond Hill Outdoor Terrace",
      slug: "richmond-hill-outdoor-terrace",
      category: "outdoor",
      location: "Richmond Hill, ON",
      year: 2024,
      description:
        "Rooftop terrace transformation with slate-look porcelain pavers, linear fire pit, and outdoor lounge furniture. The 20mm thick pavers withstand Canadian winters while looking stunning year-round.",
      productsUsed: "Slate Charcoal 24x24 Anti-Slip",
      images: ["/images/projects/project5.jpg"],
      featured: true,
    },
    {
      name: "Scarborough Bathroom Renovation",
      slug: "scarborough-bathroom-renovation",
      category: "bathroom",
      location: "Scarborough, ON",
      year: 2024,
      description:
        "Vintage-modern bathroom with hexagonal mosaic floor tiles in black and white, paired with classic white subway wall tiles. Brass fixtures and clawfoot tub complete the look.",
      productsUsed: "Hexagon Black & White Mosaic, Subway White Gloss 3x12",
      images: ["/images/projects/project6.jpg"],
      featured: true,
    },
    {
      name: "Downtown Retail Space",
      slug: "downtown-retail-space",
      category: "commercial",
      location: "Toronto, ON",
      year: 2025,
      description:
        "Fashion boutique with terrazzo-look large-format tiles and brass inlay strips creating geometric patterns. The flooring sets the tone for the entire shopping experience.",
      productsUsed: "Terrazzo Classic 24x24",
      images: ["/images/projects/project7.jpg"],
      featured: false,
    },
    {
      name: "Etobicoke Basement Suite",
      slug: "etobicoke-basement-suite",
      category: "flooring",
      location: "Etobicoke, ON",
      year: 2024,
      description:
        "Legal basement apartment with luxury vinyl plank flooring in warm grey-brown. Waterproof and durable for rental use while maintaining a premium aesthetic.",
      productsUsed: "Smoked Oak Plank 6x36",
      images: ["/images/projects/project8.jpg"],
      featured: false,
    },
    {
      name: "North York Powder Room",
      slug: "northyork-powder-room",
      category: "bathroom",
      location: "North York, ON",
      year: 2025,
      description:
        "Small but dramatic powder room with bold geometric cement tile feature wall in black, white, and terracotta. Dark ceiling, pedestal sink, and brass sconces complete the statement space.",
      productsUsed: "Cement Tile Geometric Feature",
      images: ["/images/projects/project9.jpg"],
      featured: false,
    },
    {
      name: "Markham Custom Home",
      slug: "markham-custom-home",
      category: "flooring",
      location: "Markham, ON",
      year: 2024,
      description:
        "Custom-built home with European oak engineered hardwood look porcelain throughout the open-plan main floor. High ceilings and grand staircase complement the warm flooring.",
      productsUsed: "Natural Oak Plank 8x48, Smoked Oak Plank 6x36",
      images: ["/images/projects/project10.jpg"],
      featured: false,
    },
    {
      name: "Beaches Outdoor Kitchen",
      slug: "beaches-outdoor-kitchen",
      category: "outdoor",
      location: "The Beaches, Toronto, ON",
      year: 2025,
      description:
        "Backyard outdoor kitchen with stone-look porcelain pavers, built-in grill surround in matching tile, and pergola-covered dining area. Perfect for summer entertaining.",
      productsUsed: "Stone-Look Beige 24x24 Outdoor",
      images: ["/images/projects/project11.jpg"],
      featured: false,
    },
    {
      name: "Vaughan Restaurant",
      slug: "vaughan-restaurant",
      category: "commercial",
      location: "Vaughan, ON",
      year: 2024,
      description:
        "Restaurant interior with antislip quarry tile in the kitchen and polished concrete-look tiles in the dining room. Warm pendant lighting over wooden tables creates an inviting atmosphere.",
      productsUsed: "Urban Light 24x48, Urban Dark 24x24",
      images: ["/images/projects/project12.jpg"],
      featured: false,
    },
  ]);

  console.log("Projects seeded");

  // Seed showroom
  await db.insert(showroomInfo).values({
    name: "Teranova Showroom",
    address: "1500 Dundas Street East",
    city: "Toronto",
    province: "ON",
    postalCode: "M4L 1L4",
    phone: "(416) 555-0147",
    whatsapp: "+14165550147",
    email: "hello@teranovatile.ca",
    hours: JSON.stringify([
      { day: "Monday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Tuesday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Wednesday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Thursday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Friday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Saturday", open: "9:00 AM", close: "4:00 PM" },
      { day: "Sunday", open: "Closed", close: "Closed" },
    ]),
    mapUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2885.0!2d-79.318!3d43.665!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzfCsDM5JzU0LjAiTiA3OcKwMTknMDQuOCJX!5e0!3m2!1sen!2sca!4v1",
    parkingInfo: "Free parking available at the rear of the building.",
    images: ["/images/hero/hallway.jpg", "/images/hero/kitchen.jpg"],
  });

  console.log("Showroom seeded");

  // Seed team members
  await db.insert(teamMembers).values([
    {
      name: "Marco R.",
      role: "Sales Manager",
      avatarUrl: "/images/team/marco.jpg",
      whatsappNumber: "+14165550148",
      sortOrder: 1,
      isActive: true,
    },
    {
      name: "Elena S.",
      role: "Design Consultant",
      avatarUrl: "/images/team/elena.jpg",
      whatsappNumber: "+14165550149",
      sortOrder: 2,
      isActive: true,
    },
    {
      name: "James T.",
      role: "Project Coordinator",
      avatarUrl: "/images/team/james.jpg",
      whatsappNumber: "+14165550150",
      sortOrder: 3,
      isActive: true,
    },
  ]);

  console.log("Team members seeded");
  console.log("Seed complete!");
}

seed().catch(console.error);
